. ~/bin/dotfiles/bash/env
. ~/bin/dotfiles/bash/config
. ~/bin/dotfiles/bash/aliases
. ~/bin/dotfiles/bash/git-flow-completion

### rbenv
eval "$(rbenv init -)"

### node
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"