#!/bin/bash

VERSION=$(date +"%Y-%m-%d-%H%M")
if [ -n "$1" ]; then
  VERSION="${VERSION}_${1}"
fi
echo "RELEASING ${VERSION}"

git checkout master
git pull origin master
git tag -a $VERSION -m "Release $VERSION"
git push origin master --tags